# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: $(imageRepository)
        tags: |
          $(tag)
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: 'Tenable Pay-As-You-Go(a28dd071-9504-4d90-892a-81d55ad9ac11)'
        KeyVaultName: 'TenableCSDemoKeyVault'
        SecretsFilter: '*'
        RunAsPreJob: false
    - task: ShellScript@2
      displayName: Assessing image for vulnerabilities
      inputs:
       scriptPath: tiocs-azure-on-prem-scanner.sh
       args: '$(TIOACCESSKEY) $(TIOSECRETKEY) $(TIOJFROGPASS)'

