version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker hub or it will prevent us from pulling the build due to new terms of service
      - docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
