version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "web-login-site"

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER .
