name: Super-Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: registry.cloud.tenable.com/web-login-site-via-gitactions/web-login-site
          tag_with_ref: true